PRODUCTION:
  DB_DRIVERNAME : "postgresql+psycopg2"
  DB_USERNAME : "navaandbuser"
  DB_DBNAME : "plambo"
  DB_PASSWORD : "plambo@321"
  DB_HOST: "localhost"
  DB_PORT: "5432"

DEVELOPMENT:
  DB_DRIVERNAME : "postgresql+psycopg2"
  DB_USERNAME : "postgres"
  #DB_PASSWORD : "navaan@db@123"
  DB_PASSWORD : "root"
  DB_DBNAME : "plambo"
  DB_HOST : "localhost"
  DB_PORT : "5432"
  
