PRODUCTION:
  DB_DRIVERNAME : "postgresql+psycopg2"
  DB_USERNAME : ""
  DB_DBNAME : ""
  DB_PASSWORD : ""
  DB_HOST: "localhost"
  DB_PORT: "5432"

DEVELOPMENT:
  DB_DRIVERNAME : "postgresql+psycopg2"
  DB_USERNAME : "postgres"
  #DB_PASSWORD : ""
  DB_PASSWORD : ""
  DB_DBNAME : ""
  DB_HOST : "localhost"
  DB_PORT : "5432"
  
