DEVELOPMENT:
  DB_DRIVERNAME : "postgresql+psycopg2"
  DB_USERNAME : "postgres"
  #DB_PASSWORD : "navaan@db@123"
  DB_PASSWORD : "root"
  DB_DBNAME : "Plambo"
  DB_HOST : "localhost"
  DB_PORT : "5432"